#!/bin/bash

if [ $1 == "2mb" ]; then
        csize="2mb"
        p1=0x3 
        p2=0xffffc
        module=/home/ahmad/scheduler_2mb
elif [ $1 == "3mb" ]; then
        csize="3mb"
        p1=0x7 
        p2=0xffff8
        module=/home/ahmad/scheduler_3mb
elif [ $1 == "4mb" ]; then 
        csize="4mb"
        p1=0xf 
        p2=0xffff0
        module=/home/ahmad/scheduler_4mb
fi

echo setting cache size to: $csize

cat=/home/ahmad/catConfig
srun_cs_path=/home/ahmad/benchmarks/run_cloudsuite
hserver_bmk=$srun_cs_path/servers
hclient_bmk=$srun_cs_path/clients
hresults=$srun_cs_path/results/$csize
crun_cs_path=/home/ubuntu/run_cloudsuite
cserver_bmk=$crun_cs_path/servers
cclient_bmk=$crun_cs_path/clients
cresults=$crun_cs_path/results/$csize

ssh_command="ssh root@525-1.behrat.net"
weave_eval="eval $(weave env)"

eval $(weave env)

##danalytics with other bmks
$srun_cs_path/docker_cleanup
$ssh_command "$crun_cs_path/docker_cleanup"

rmmod scheduler_km
$cat/reset_cat.sh

##run wserving bmk
$hserver_bmk/wserving_server
$ssh_command "$weave_eval && $cclient_bmk/wserving_client $cclient_bmk background 4-7"
echo wserving bmk launched....

##run danalytics bmk
$hserver_bmk/danalytics_server $hresults/danalytics/with_wserving_base 

##config 
$srun_cs_path/docker_cleanup
$ssh_command "$crun_cs_path/docker_cleanup"
$cat/single_cat.sh $p1 $p2

##run wserving bmk
$hserver_bmk/wserving_server
$ssh_command "$weave_eval && $cclient_bmk/wserving_client $cclient_bmk background 4-7"
echo wserving bmk launched....

##run danalytics bmk
$hserver_bmk/danalytics_server $hresults/danalytics/with_wserving_partitioned 

##config 
$srun_cs_path/docker_cleanup
$ssh_command "$crun_cs_path/docker_cleanup"
insmod $module/scheduler_km.ko

##run wserving bmk
$hserver_bmk/wserving_server
$ssh_command "$weave_eval && $cclient_bmk/wserving_client $cclient_bmk background 4-7"
echo wserving bmk launched....

##run danalytics bmk
$hserver_bmk/danalytics_server $hresults/danalytics/with_wserving_flush 

echo ---------------TESTS WITH WSERVING COMPLETE---------------------------------

echo ------------------------TESTS WITH DCACHING STARTING------------------------------

$srun_cs_path/docker_cleanup
$ssh_command "$crun_cs_path/docker_cleanup"
rmmod scheduler_km
$cat/reset_cat.sh

#run dcaching bmk
$hserver_bmk/dcaching_server
$ssh_command "$weave_eval && $cclient_bmk/dcaching_client background 4-7"
sleep 15

##run danalytics bmk
$hserver_bmk/danalytics_server $hresults/danalytics/with_dcaching_base 

#config 
$srun_cs_path/docker_cleanup
$ssh_command "$crun_cs_path/docker_cleanup"
$cat/single_cat.sh $p1 $p2

#run dcaching bmk
$hserver_bmk/dcaching_server
$ssh_command "$weave_eval && $cclient_bmk/dcaching_client background 4-7"
sleep 15

##run danalytics bmk
$hserver_bmk/danalytics_server $hresults/danalytics/with_dcaching_partitioned 

##config 
$srun_cs_path/docker_cleanup
$ssh_command "$crun_cs_path/docker_cleanup"
insmod $module/scheduler_km.ko

#run dcaching bmk
$hserver_bmk/dcaching_server
$ssh_command "$weave_eval && $cclient_bmk/dcaching_client background 4-7"
sleep 15

##run danalytics bmk
$hserver_bmk/danalytics_server $hresults/danalytics/with_dcaching_flush 

echo ----------------------TESTS WITH DCACHING COMPLETE-------------------------

echo -----------------------TEST WITH GOBMK STARTING---------------------------------

$srun_cs_path/docker_cleanup
$ssh_command "$crun_cs_path/docker_cleanup"

cat=/home/ahmad/catConfig
bmk=$(pwd)/run_cloudsuite
results=$(pwd)/run_cloudsuite/results/$csize

###dataanalytics with other bmks
$bmk/docker_cleanup
rmmod scheduler_km
$cat/reset_cat.sh

##run data_caching bmk
$bmk/run_datacaching 'background'
sleep 20

##run dataanlytics bmk
$bmk/run_dataanalytics $results/dataanlytics/with_datacaching_base.xml

##config 
$bmk/docker_cleanup
$cat/single_cat.sh 0x3 0xffffc

##run data_caching bmk
$bmk/run_datacaching 'background'
sleep 20

##run dataanlytics bmk
$bmk/run_dataanalytics $results/dataanlytics/with_datacaching_partitioned.xml

##config 
$bmk/docker_cleanup
insmod $module/scheduler_km.ko

##run data_caching bmk
$bmk/run_datacaching 'background'
sleep 20

##run dataanlytics bmk
$bmk/run_dataanalytics $results/dataanlytics/with_datacaching_flush.xml

echo ---------------TESTS WITH GOBMK COMPLETE---------------------------------

echo -----------------------TEST WITH DSERVING STARTING---------------------------------

$srun_cs_path/docker_cleanup
$ssh_command "$crun_cs_path/docker_cleanup"
rmmod scheduler_km
$cat/reset_cat.sh

#run dataserving bmk
$hserver_bmk/dserving_server
$ssh_command "$weave_eval && $cclient_bmk/dserving_client background 4-7"
sleep 15

#run danalytics bmk
$hserver_bmk/danalytics_server $hresults/danalytics/with_dserving_base 

##config 
$srun_cs_path/docker_cleanup
$ssh_command "$crun_cs_path/docker_cleanup"
$cat/single_cat.sh $p1 $p2

#run dataserving bmk
$hserver_bmk/dserving_server
$ssh_command "$weave_eval && $cclient_bmk/dserving_client background 4-7"
sleep 15

#run danalytics bmk
$hserver_bmk/danalytics_server $hresults/danalytics/with_dserving_partitioned 

##config 
$srun_cs_path/docker_cleanup
$ssh_command "$crun_cs_path/docker_cleanup"
insmod $module/scheduler_km.ko

#run dataserving bmk
$hserver_bmk/dserving_server
$ssh_command "$weave_eval && $cclient_bmk/dserving_client background 4-7"
sleep 15

#run danalytics bmk
$hserver_bmk/danalytics_server $hresults/danalytics/with_dserving_flush 

echo -----------------------TEST WITH DATASERVING COMPLETE---------------------------------
