#!/bin/bash

#Scales twitter dataset to 10x=3GB and send 10k requests/second.
#Reduce the number of server threads to 1 and client threads to 4
#Reduced client connections to 80

cores=$2

docker run -t -d --cpuset-cpus=$2 --name dc-client --net caching_network mohdahmad/data-caching:client bash

sleep 3

if [ $1 == 'background' ]; then #run without a timeout
        echo Running data caching bmk without a timeout
        docker exec -d -t dc-client bash -c "cd /usr/src/memcached/memcached_client/; ./loader -a ../twitter_dataset/twitter_dataset_10x -s docker_servers.txt -g 0.8 -T 240 -c 80 -w 4 -e -r 10000"
else #run with a timeout
        echo Running data caching bmk with a timeout
        docker exec -t dc-client bash -c "cd /usr/src/memcached/memcached_client/; ./loader -a ../twitter_dataset/twitter_dataset_10x -s docker_servers.txt -g 0.8 -T 240 -t 720 -c 80 -w 4 -e -r 10000" > $1
fi
