#!/bin/bash

#kill all containers apart from the weave containers
docker kill $(docker ps | awk '!/weave/ {print $1}' | tail -n+2)


#rm all containers apart from the weave containers
docker rm -f $(docker ps -a | awk '!/weave/ {print $1}' | tail -n+2)

