#!/bin/bash

#4 million operations from the read-heavy ycsb workload (95% reads)
docker exec -dt mongodb-bench bash -c "cd /usr/local/ycsb-0.5.0 ; ./bin/ycsb run mongodb-async -s -P workloads/workloadb > outputRun.txt -p operationcount=4000000; cat outputRun.txt"
sleep 15
