#!/bin/bash

docker run --cpuset-cpus="8" --name mongodb-server -d -t mohdahmad/mongodb-test:0.4
echo "launched container..."

docker exec -t -d mongodb-server bash -c "cd /home/mongodb-linux-x86_64-3.2.6 ; ./bin/mongod --dbpath /tmp/mongodb"
echo "started mongoDb..."
sleep 30
